spring:
  data:
    web:
      pageable:
        pageable:
          default-page-size: 20
          max-page-size: 100
          one-indexed-parameters: false
          page-parameter: page
          size-parameter: size
          sort:
            sort-parameter: sort